import { StyleSheet } from 'react-native';

const Estilos = StyleSheet.create({
    textInput:{
        borderWidth:1,
        borderColor:'#000',
        borderRadius:10,
        width:'90%',
        height:50,
        alignSelf:'center',
        marginTop:'2%',
        padding:10
    },
    btn:{
        width:'90%',
        height:50,
        borderWidth:1,
        borderBottomColor:'000',
        borderRadius:25, 
        alignItems:'center',
        justifyContent:'center',
        marginBottom: 10
    },
    configList:{
        flex:1,
        flexDirection:'row',
        width:'90%',
        height:50, 
        alignSelf:'center',
        justifyContent:'flex-start',
        borderWidth:1, 
        borderColor:'#000', 
        borderRadius: 10,
        padding:10,
        marginTop:'1%'
    },
    imgList:{
        width:30,
        height:30,
        borderRadius:15
    },
    txtList:{
        flex:1,
        fontSize:12,
        paddingTop:5,
        marginLeft:10
    },
    iconList:{
        width:23,
        height:23,
        marginTop:2
    },
    containerInput:{
        marginTop:'2%', 
        marginBottom:'3%',
        width:'100%',
        height:65,
        alignSelf:'center'
    },
    containerList:{
        flex:1, 
        borderWidth:1, 
        borderColor:'#000', 
        width:'90%',
        marginBottom:10,
        marginTop:10,
        alignSelf:'center', 
        borderRadius:5
    },
    listaPesquisa:{
        flexDirection:'row',
        justifyContent:'space-between',
        borderBottomWidth:1,
        borderBottomColor:'#000',
        alignItems:'center'
    },
    iconDelete:{
        width:25,
        height:25,
        marginRight:13
    },
    imgReceitas:{
        width:50,
        height:50, 
        borderRadius:25
    },
    txtReceitas:{
        fontSize:18,
        padding:12
    },
    imgInfoReceitas:{
        width:200,
        height:200,
        borderRadius:100,
        justifyContent:'center'
    },
    txtInfoReceitas:{
        fontSize:18,
        padding:3,
        marginLeft:5
    }
})

export default Estilos;